Updated test_hca2scea.py
ebi-ait/hca-to-scea-tools pull request #53
Opened 2021-10-04 11:12 UTC by ami-day

Updated test_hca2scea.py file to provide the correct path to the expected test output files.
Also updated .gitignore file to ignore directories where output gets automatically added when the script is run.

2021-10-16 21:34 UTC, amnonkhen requested changes

2021-10-16 21:34 UTC, amnonkhen commented on hca2scea-backend/test_hca2scea.py
> +                self.check_output(os.path.join("test/golden",output_dir), spreadsheet)
What is the purpose of this change?
You should not generate anything in the "golden" directory.

2021-10-16 21:36 UTC, amnonkhen commented
Please name the branch according to the feature you are implementing and with a ticket number in it, e.g. `feature/add-xyz-feature-dcp-123`

2021-10-21 16:20 UTC, ami-day commented on hca2scea-backend/test_hca2scea.py
> +                self.check_output(os.path.join("test/golden",output_dir), spreadsheet)
Ohhh yes I see. This is wrong. I was confused when I changed this.

2021-10-21 16:21 UTC, ami-day commented
> Please name the branch according to the feature you are implementing and with a ticket number in it, e.g. `feature/add-xyz-feature-dcp-123`

Will do from now on

2021-10-21 16:22 UTC, ami-day commented
I think this branch should actually be deleted. The characteristic test is working fine in my latest pull request/a different branch.

2021-10-21 16:45 UTC, closed without merging