Update to hca2scea tool: automatically obtain fastq file paths or SRA file paths
ebi-ait/hca-to-scea-tools pull request #54
Opened 2021-10-05 16:45 UTC by ami-day

This is a pull request for an update to the hca-to-scea-tools repo. In particular, the main "script.py" script, and also the addition of a "fetch_fastq_path.py" module. 
The update enables the script to automatically get the fastq file paths or SRA file paths based on the list of run accessions and also the relevant file names. This information is automatically added into the output sdrf file.

2021-10-05 20:14 UTC, amnonkhen requested changes
code needs lots of cleanup

2021-10-06 09:00 UTC, ami-day commented
> Thanks, @ami-day, for the PR.
> 
> A few comments:
> 
> 1. How are the new features tested? I did not notice any change to the test files.
> 2. Keeping the code as it is, albeit maybe functionally correct, would be incurring a big technical debt. It would be very difficult for us as a team, and even for you who wrote this, to maintain, modify, fix and extend it with confidence.
> 3. One of the test scenarios is currently failing.

Thanks for the quick review @amnonkhen, I agree, I'll next work on adding feature tests for this and also spend some time refactoring the code so it is maintainable. I'll work on this this sprint as I'm on development. Will have a look at why 1 of the tests is failing.

2021-10-07 14:27 UTC, amnonkhen requested changes

2021-10-07 14:27 UTC, amnonkhen commented on hca2scea-backend/fetch_fastq_path.py
> +    runs = list(sdrf['Comment[ENA_RUN]'])
cleanup tip:
This a classic TMI method (Too Much Information)
There is too much detail here.
I would extract bits of it to properly named functions.
For example, the read1 bits, the read2 bits, processing a run.
Would you like to do a few examples together?

2021-10-08 14:14 UTC, ami-day commented on hca2scea-backend/fetch_fastq_path.py
> +    runs = list(sdrf['Comment[ENA_RUN]'])
Yes, this is the type of thing I'd love feedback on. I'm going to finish my 1st session of re-organising/refactoring the code, and then going through examples like this to improve further would be great.

2021-10-08 14:15 UTC, ami-day commented on hca2scea-backend/fetch_fastq_path.py
> +    runs = list(sdrf['Comment[ENA_RUN]'])
I haven't yet refactored the code for this particular new functionality. I have approached the entire script.

2021-10-15 13:26 UTC, ami-day commented
Hi @amnonkhen I am finished with my refactoring and added some checks for expected output at the end. It seems to me the tests are working with updated expected output files. I'd like to get this pull request soon so I can move onto updating it with new features. Shall we go through how you would approach improving the code first? What's best for you?

2021-10-22 13:32 UTC, merged