Feature 69 Create pypi package
ebi-ait/hca-to-scea-tools pull request #72
Opened 2022-03-01 11:24 UTC by ami-day

Created a setup.py file
Creaated an SCEA_curatoin_guidelines file: moved some of the guidelines from the README.md file to this new md file.
Created a new README.md file which is more suitable for a pypi package.
Added __init__.py files
Added requirements.txt file

2022-03-01 11:39 UTC, jacobwindsor requested changes
A few things but great job!

2022-03-01 11:39 UTC, jacobwindsor commented on setup.py
> +    version="1.0.0",
I think this should be v0.1.0. See [https://semver.org/](Semver versioning). New projects start at v0

2022-03-01 11:39 UTC, jacobwindsor commented on setup.py
> +    author_email="ami@ebi.ac.uk, javier.f.g@um.es, yhaider@ebi.ac.uk, aaclan@ebi.ac.uk",
Typically this would be in order of who to contact with issues

2022-03-01 11:39 UTC, jacobwindsor commented on MANIFEST.in
> +include requirements.txt
You dont need to specify requirements.txt in the MANIFEST. So just remove it

2022-03-01 11:39 UTC, jacobwindsor commented on README.md
> +    pip install -e path/to/hca-to-scea
`pip install -e . ` is better

2022-03-01 11:39 UTC, jacobwindsor commented on requirements.txt
> +brotlipy=0.7.0=py39hcbf5805_1001
How was this file created? I've not seen versioning with the py39... 

Also, please use less strict versioning. Typically we just version on major releases unless we know that we need a minor version for some reason. See https://www.python.org/dev/peps/pep-0440/#version-specifiers

2022-03-02 10:04 UTC, ami-day reviewed
Thanks Jacob, I have made the suggested changes except I need to ask you about the requirements versioning. I have a couple of other questions too, I'll message you on slack.

2022-03-04 09:45 UTC, ESapenaVentura commented
Still working on this

2022-03-04 17:48 UTC, jacobwindsor requested changes
Have you tried installing this? `pip install .`

I get the error "ERROR: Could not find a version that satisfies the requirement sqlite (from hca-to-scea)
"

2022-03-07 22:18 UTC, amnonkhen requested changes
There seems to be a great mess here.
Many of these files should not be part of the PR, as they are files I have changed in a previous PR.
I need you to walk me through the steps you have taken to get here, as it appears that something went wrong on the way.

2022-03-07 22:21 UTC, amnonkhen commented
> Created a setup.py file Creaated an SCEA_curatoin_guidelines file: moved some of the guidelines from the README.md file to this new md file. Created a new README.md file which is more suitable for a pypi package. Added **init**.py files Added requirements.txt file

No need for such comments as it is clear in the PR which file is added, modified or deleted.
It is more helpful to use informative sentences like "added package build scripts" or "update documentation with XYZ"

2022-03-16 10:12 UTC, merged