Check for floating point number and reformat it.
ebi-ait/hca-to-scea-tools pull request #81
Opened 2022-03-22 14:43 UTC by ami-day

dcp-79
Fix floating point error issue in idf file. It causes the tests to fail. The pmid should not be a floating point number, it should be a string or integer.

2022-03-22 15:00 UTC, jacobwindsor requested changes
I don't see the reason for this. Wouldn't it be better just to fix the input data than cater for an edge case of having float values for a PMID? A float value for a PMID is not valid anyway so we should not have that in our DB and if we do we should fix it. We shouldn't be catering for invalid data, we shouldn't allow invalid data

2022-03-22 15:00 UTC, jacobwindsor commented on build/lib/hca_to_scea/helpers/cell_lines.py
> +import pandas as pd
Ths build directory should not appear in any branch. Please remove and gitignore it

2022-03-24 09:47 UTC, idazucchi commented
@amnonkhen to review

2022-03-28 08:56 UTC, amnonkhen requested changes

2022-03-28 08:56 UTC, amnonkhen commented on hca-to-scea/script_spreadsheets/SRP151260/E-HCAD-44.idf.txt
> +
What is this `scripts_scpreadsheets` directory?
Which script uses it?
We already have a directory for the test inputs and the expected outputs.
The directory of files generated during the test run should not be added to git. If it is, delete it and add an entry to gitignore.

2022-09-01 16:31 UTC, ami-day commented
Im closing this pull request as this has already been done and merged in a separate branch.

2022-09-01 16:31 UTC, closed without merging